### ISSUE TITLE
encodage de l'apostrophe

### ISSUE THREAD

**Issue by jrenierhenix** [prosanteconnect/squash-plugin#13]
Dans la colonne "Scénario de conformité", les apostrophes présents dans les textes ressortent avec l'encodage html **&eapos;** , ils devraient être convertis en caractère.
![2022-05-20 16_59_51-_id_rsa pub - Bloc-notes](https://user-images.githubusercontent.com/105277796/169556213-a6d6e714-4f24-43a1-8ef9-c4c14288bb4a.png)

**Comment by pam199968** [comment]
`&apos;` n'est pas une entité html compatible, il faut utiliser `&#39;` à la place.
C'est étonnant que dans les exigences, c'est correctement échappé et pas dans les tests.
Si le bug est dans squash, il faudra faire une correction maison.
