### ISSUE TITLE
problème d'accents

### ISSUE THREAD

**Issue by jrenierhenix** [prosanteconnect/squash-plugin#17]
Il se passe un truc très étrange avec les cellules contenant des caractères autres que ascii standard (accents, apostrophes, ...).

La cellule est correctement affichée.
![image](https://user-images.githubusercontent.com/105277796/170070391-34cc3d38-87c8-4929-ad82-7c9b9267bffa.png)

Mais si on double-clique dedans pour l'éditer, excel affiche des caractères très étranges à la place de certaines lettres.
![image](https://user-images.githubusercontent.com/105277796/170070470-5cc75a3a-541a-4ba5-b524-32236fd2ddfb.png)

problème d'encodage UTF8 ?

**Comment by pam199968** [comment]
Bonjour,
je n'arrive pas à reproduire le comportement.
