### ISSUE TITLE
tri des exigences

### ISSUE THREAD

**Issue by jrenierhenix** [prosanteconnect/squash-plugin#20]
Les lignes du tableau Excel devraient être triées selon cet ordre : 
1/ par section : 
 a)  en premier toutes les sections des socles, dans cet ordre : INS, DMP, MSS, PSC, ANN, TBB, HOP, DOC, PORT, EPR
 b) puis toutes les autres sections triées par ordre alpha

2/ puis par référence d'exigence (tri alpha montant)

3/ puis par référence de scénario (tri alpha montant)

NB : pour le tri par défaut des section, pour éviter de le mettre en dur dans le code, peut-on capitaliser sur une information dynamique rattachée aux projets ? champ description ou autre.. si tu as des propositions....

**Comment by pam199968** [comment]
Bonjour,
Est-il possible d'ajouter un champ personnalisé (ordre) sur les sections ?

**Comment by jrenierhenix** [comment]
j'ouvre ce ticket pour demander une évolution : 

Dans les nouveaux référentiel vague 2, l'ANS a voulu créer la notion de sous-section.
Par exemple, dans la section `MSS`, on va avoir maintenant `MSS/UX` et `MS/CONF` 

Pour le tri, qui place en priorité les exigences des sections listées (INS, DMP, MSS, PSC, ANN, TBB, HOP, DOC, PORT, EPR), il faudrait inclure les sous section comme appartenant aux sections.
par exemple, la clef de tri de `MSS/CONF` doit être `MSS`

Autrement dit, on veut retrouver tous les `MSS/xxx`  regroupés au même endroit que les `MSS`

De même pour les autres sections (ça ne concerne pas que MSS)

![image](https://user-images.githubusercontent.com/105277796/193220211-afe716a0-4078-4b2e-904f-da8b4fefecd3.png)

**Comment by jrenierhenix** [comment]
demande toujours d'actualité, est-il possible d'apporter un correctif ?
