### ISSUE TITLE
référence des exigences "PSC"

### ISSUE THREAD

**Issue by jrenierhenix** [prosanteconnect/squash-plugin#31]
Dans le référentiel il existe un socle PSC (par exemple : SC.PSC.03)
lors de l'export REM, les références de ces exigences sont incorrectes : 
Par exemple au lieu de "PSC.03", il est affiché "03"

Il semblerait que le terme "SC" présent dans "P**SC**" interfère avec la fonction de substitution qui retire le préfixe "SC." des exigences.

**Comment by pam199968** [comment]
Les exigences rattachées à une exigence socle ne sont plus traitées pour supprimer le préfixe.
